name: mkdocs-to-gh-pages
on:
  push:
    branches:
      - 4-document-procedure-for-new-reader-type-creation

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --local user.name ${{ secrets.PAGES_USER }}
          git config --local user.email ${{ secrets.PAGES_EMAIL }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: pip install mkdocs-autorefs
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings
      - run: mkdocs gh-deploy
